In [73]:
from sklearn.linear_model import ElasticNet
from sklearn.metrics import r2_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet , BayesianRidge , SGDRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor , AdaBoostRegressor

In [38]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Define the data
data = {
    "Umin(mm)": [1.000061],
    "Fmin(N)": [91.884211],
    "Umax(mm)": [9.114439],
    "Fmax(N)": [2614.567],
    "p1(N/mm)": [160.2600046],
    "p2(N/mm)": [181.4367527],
    "ptflexion(mm)": [6.8016]
}

# Create DataFrame
df_test = pd.DataFrame(data)

print(df_test)

   Umin(mm)    Fmin(N)  Umax(mm)   Fmax(N)    p1(N/mm)    p2(N/mm)  \
0  1.000061  91.884211  9.114439  2614.567  160.260005  181.436753

   ptflexion(mm)
0         6.8016

In [39]:
df = pd.read_excel('C:/Users/yasmi/Downloads/data_JC.xls', sheet_name="Feuil1")

df.head()

,A(MPa),B(MPa),n,Umin(mm),Fmin(N),Umax(mm),Fmax(N),p1(N/mm),p2(N/mm),ptflexion(mm)
0,10,90,0.2,0.472616,132.514948,9.406141,1828.338135,-41.048167,128.671351,5.846848
1,45,90,0.2,0.472787,151.169610,9.403861,2582.698486,-40.003432,145.262882,4.290309
2,80,90,0.2,0.472771,194.113349,9.417878,3347.173828,-109.336813,186.211358,3.454615
3,10,145,0.2,0.472679,126.031387,9.416237,2814.554688,30.753123,205.591396,5.586041
4,45,145,0.2,0.472779,167.995440,9.408020,3576.553467,-90.515814,254.893251,5.236132

In [43]:
df_test

,Umin(mm),Fmin(N),Umax(mm),Fmax(N),p1(N/mm),p2(N/mm),ptflexion(mm)
0,1.000061,91.884211,9.114439,2614.567,160.260005,181.436753,6.8016

In [62]:
X= df.drop(columns = ['A(MPa)' , 'B(MPa)' , 'n'], axis=1)
y = df[['A(MPa)' , 'B(MPa)' , 'n']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [67]:
from sklearn.linear_model import ElasticNet
from sklearn.metrics import r2_score

# Recreate model with the best parameters
model = MultiOutputRegressor(ElasticNet(alpha=0.01, l1_ratio=0.1, max_iter=1000))

# Fit on training data
model.fit(X_train, y_train)

# Predict on test data
y_pred = model.predict(X_test)

# Evaluate with R²
r2 = r2_score(y_test, y_pred)
print("R² score:", r2)
y_pred = model.predict(df_test)

# Store predictions by sample ID
predictions["25"] = y_pred[0]   # first row (corresponds to your df_test sample)

# Print each target
print("A:", predictions["25"][0],
      "B:", predictions["25"][1],
      "n:", predictions["25"][2])

R² score: 0.5213267557326359
A: 22.60674092964387 B: 126.72082888532364 n: 0.3290755745759507

In [78]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

# Recreate Random Forest with best parameters
model = MultiOutputRegressor(RandomForestRegressor(max_depth=10,min_samples_split=5,n_estimators=100,random_state=42))
#model = MultiOutputRegressor(ElasticNet(alpha=0.01, l1_ratio=0.1, max_iter=1000))
#model = MultiOutputRegressor(GradientBoostingRegressor(learning_rate=0.01, max_depth=3,n_estimators=100,random_state=4 ))


# Fit on training data
model.fit(X_train, y_train)

# Predict on test data
y_pred = model.predict(X_test)

# Evaluate with R²
r2 = r2_score(y_test, y_pred, multioutput='uniform_average')
print("R² score:", r2)

# ---- Predict on your new sample (df_test) ----
y_new = model.predict(df_test)

print("Predicted outputs for df_test:", y_new)

# If y is multi-output (A, B, n)
print("A:", y_new[0][0],
      "B:", y_new[0][1],
      "n:", y_new[0][2])

R² score: 0.6462746944068612
Predicted outputs for df_test: [[ 29.48625    113.40992063   0.41542679]]
A: 29.48625 B: 113.40992063492064 n: 0.4154267857142858