In [14]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split , GridSearchCV

from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet , BayesianRidge , SGDRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor , AdaBoostRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.kernel_ridge import KernelRidge
from catboost import CatBoostRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.neural_network import MLPRegressor

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, median_absolute_error

In [15]:
df = pd.read_excel('C:/Users/yasmi/Downloads/logistic_data_v1.xlsx', engine='openpyxl')

In [16]:
X= df.drop(columns = ['K(MPa)' , 'epsilon_0' , 'n'], axis=1)
y = df['n']

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=42)

In [18]:
model = CatBoostRegressor(iterations=1000, depth=6, learning_rate=0.05, random_seed=42, verbose=0)
#model = DecisionTreeRegressor(max_depth=10, min_samples_split=10, random_state=42)
model.fit(X_train, y_train)

In [19]:
X_train_df = pd.DataFrame(X_train)
X_test_df = pd.DataFrame(X_test, columns=X_train_df.columns)
    
y_pred = model.predict(X_test_df)

y_pred = y_pred.flatten()


r2 = r2_score(y_test, y_pred)





print(r2)

0.9926310619468757

In [20]:
df_test25 = pd.read_excel("C:/Users/yasmi/Downloads/Indices de forme (3).xlsx", engine='openpyxl' , sheet_name="25")
df_test25.head()

   Umin(mm)  Fmin(N)  Uint(mm)  Fint(N)  Umax(mm)  Fmax(N)    pente1  pente2
0    1.1646   1552.8    4.2725   2461.6   17.7551   2496.6  292.4223  2.5941

In [21]:
df_test100 = pd.read_excel("C:/Users/yasmi/Downloads/Indices de forme (3).xlsx", engine='openpyxl' , sheet_name="100")
df_test100.head()

   Umin(mm)  Fmin(N)  Uint(mm)  Fint(N)  Umax(mm)  Fmax(N)    pente1  pente2
0    1.0394   1528.7    3.9565   2327.9   16.4003   2347.6  273.9581  1.5819

In [22]:
df_test150 = pd.read_excel("C:/Users/yasmi/Downloads/Indices de forme (3).xlsx", engine='openpyxl' , sheet_name="150")
df_test150.head()

   Umin(mm)  Fmin(N)  Uint(mm)  Fint(N)  Umax(mm)  Fmax(N)    pente1  pente2
0    1.0147   1484.8    3.9885   2244.8   16.6332   2246.9  255.5575   0.168

In [23]:
df_test200 = pd.read_excel("C:/Users/yasmi/Downloads/Indices de forme (3).xlsx", engine='openpyxl' , sheet_name="200")
df_test200.head()

   Umin(mm)  Fmin(N)  Uint(mm)  Fint(N)  Umax(mm)  Fmax(N)    pente1  pente2
0    0.5813   1272.9    3.3643   2170.5   15.7579   2198.6  322.5548  2.2628

In [24]:
prediction25 = model.predict(df_test25)
prediction100 = model.predict(df_test100)
prediction150 = model.predict(df_test150)
prediction200 = model.predict(df_test200)

print(prediction25 , " 25 ")
print(prediction100, " 100")
print(prediction150 , "150 ")
print(prediction200 , " 200")

[0.27758297]  25
[0.25416692]  100
[0.25114875] 150
[0.23701364]  200